name: Build PDF

on:
  push:
    branches: ["**"]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t latex-build .

      - name: Build PDF
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace latex-build make f-build

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: pdf
          path: tex/main.pdf
