name: Build PDF

on:
  push:
    branches: ["**"]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/paperist/texlive-ja:latest
    steps:
      - uses: actions/checkout@v4

      - name: Build (no format)
        env:
          CI: "1"   # 画像ダミー化やCI専用設定を有効化
        run: make f-build

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: pdf
          path: tex/main.pdf
